---
title: ""
---

**Current positions**

-   Full Professor - Università degli Studi di Milano Bicocca, Italy (since jul 2025)

**Previous positions**

-   Associate Professor - Università degli Studi di Milano Bicocca, Italy (oct 2019 - jun 2025)

-   Assistant Professor - Trinity College Dublin, Ireland (feb 2016 - sep 2019)

-   Research Affiliate - "de Castro" Statistics Initiative, Collegio Carlo Alberto, Italy (2012 - 2020)

-   Visiting Research Fellow - TILDA, Trinity College Dublin, Ireland (2018-2020) 

-   Course Director - Data Science strand, M.Sc. in Computer Science, Trinity College, Dublin, Ireland (jul 2017 - sep 2019)

-   Postdoctoral Fellow - University of Torino and Collegio Carlo Alberto, Italy (sep 2012 - jan 2016)

-   Visiting postdoctoral Fellow - MD Anderson Cancer Center, Houston, USA (jan 2012 - jul 2012)

-   Research Assistant - Collegio Carlo Alberto, Italy (jul 2010 - aug 2012)\

**Editorial activity**

-   Associate Editor - Statistics and Probability Letters (may 2024 - )

-   Associate Editor - Computational Statistics & Data Analysis (may 2018 - may 2024 )

-   Reviewer for Mathematical Reviews/MathSciNet (2015 - 2022) and zbMATH (2015 - 2022) 

**Education**

-   PhD in Mathematics and Statistics - University of Pavia, Italy (jun 2011)

-   Master Degree in Mathematics - Università degli Studi di Milano-Bicocca, Italy (mar 2007)

-   Bachelor Degree in Mathematics - Università degli Studi di Milano-Bicocca, Italy (nov 2004)\

**Awards**

-   Honorable Mention, Savage Award 2012 - American Statistical Association, ISBA and NBER-NSF (aug 2013)

-   Award for Best 2011 PhD thesis in Statistics - Italian Statistical Society (jun 2012)
