---
title: ""
---

**Submitted work**

-   D'Angelo, L., Nipoti, B. & Ongaro, A. (2026+)\
    Dependent Dirichlet processes via thinning ([arXiv](https://arxiv.org/abs/2506.18223){style="text-decoration: none"})

**Publications in referred journals**

1.  Bi, J., Borrotti, M. & Nipoti, B. (2026)\
    Uncertainty quantification and multi-stage variable selection for personalized treatment regimes\
    *Biometrics*, 82(2), ujag081 ([arXiv](https://arxiv.org/abs/2411.02123){style="text-decoration: none"})

2.  Barile, F., Lunagomez, S. & Nipoti, B. (2026)\
    Bayesian nonparametric modeling of heterogeneous populations of networks\
    *Bayesian Analysis*, to appear ([arXiv](https://arxiv.org/abs/2410.10354){style="text-decoration: none"})

3.  Bissiri, P.G., Nipoti, B., Porcu, E. & White, P. (2026)\
    A non-parametric framework for correlation functions on product metric spaces\
    *International Statistical Review*, early view ([doi](https://doi.org/10.1111/insr.70026){style="text-decoration: none"})

4.  Perlino, F.L., Nipoti, B., Paige, W. & Bellavia, A. (2025)\
    A Bayesian parametric and nonparametric approach for the imputation of multivariate left-censored data due to limit of detection\
    *Statistics in Medicine*, 44(28-30), e70326

5.  Giampino. A., Nipoti, B., Vannucci, M. & Guindani, M. (2025)\
    Local Level Dynamic Random Partition Models for Changepoint Detection\
    *Bayesian Analysis*, advance publication ([doi](https://doi.org/10.1214/25-BA1560){style="text-decoration: none"}) ([arXiv](https://arxiv.org/abs/2407.20085){style="text-decoration: none"})

6.  Giampino. A., Canale, A. & Nipoti, B. (2025)\
    A Bayesian Model for Co-clustering Ordinal Data with Informative Missing Entries\
    *Statistics and Computing*, 35(5), 164

7.  Nipoti, B. & Schiavon, L. (2025)\
    Expected goals under a Bayesian viewpoint: uncertainty quantification and online learning\
    *Journal of Quantitative Analysis in Sport*, vol. 21, no. 1, pp. 37-50

8.  Hernández, B., Dyer, A.H., Finucane, C., Nipoti, B., Romero-Ortuno, R., Reilly, R. & Kenny, R.A. (2024)\
    The impact of type 2 diabetes on peripheral and cerebral haemodynamic responses to active stand\
    *Journal of Gerontology: Medical Sciences*, 79(5), p.glae073

9.  Schiavon, L., Canale, A. & Nipoti, B. (2024)\
    Accelerated structured matrix factorization\
    *Journal of Computational and Graphical Statistics*, pp.1-11 ([arXiv](https://arxiv.org/abs/2212.06504){style="text-decoration: none"})

10. Canale, A., Lijoi A., Nipoti, B. & Pruenster, I. (2023)\
    Inner spike and slab Bayesian nonparametric models\
    *Econometrics and Statistics (Part B: Statistics)*, 27, 120-135 ([arXiv](https://arxiv.org/abs/2107.10223){style="text-decoration: none"})

11. Bissiri, P.G., Cleanthous, G., Emery, X.M., Nipoti, B. & Porcu, E. (2022)\
    Nonparametric Bayesian modelling of longitudinally integrated covariance functions on spheres\
    *Computational Statistics & Data Analysis*, 176, 107555

12. Canale, A., Corradin, R. & Nipoti, B. (2022)\
    Importance conditional sampler for Pitman-Yor mixtures\
    *Statistics and Computing*, 32(40), 1-18 ([arXiv](https://arxiv.org/abs/1906.08147){style="text-decoration: none"})

13. Corradin, R., Nieto-Barajas, L.E. & Nipoti, B. (2022)\
    Optimal stratification of survival data via Bayesian nonparametric mixtures\
    *Econometrics and Statistics (Part B: Statistics)*, 22, 17-39 ([arXiv](https://arxiv.org/abs/2103.09305){style="text-decoration: none"})

14. Corradin, R., Canale, A. & Nipoti, B. (2021)\
    BNPmix: an R package for Bayesian nonparametric modelling via Pitman-Yor mixtures\
    *Journal of Statistical Software*, 100(15), 1-33 ([R package](https://cran.r-project.org/web/packages/BNPmix/index.html){style="text-decoration: none"})

15. Arbel, J., Corradin, R. & Nipoti, B. (2021)\
    Dirichlet process mixtures under affine transformations of the data\
    *Computational Statistics*, 36(1), 577-601 ([arXiv](https://arxiv.org/abs/1809.02463){style="text-decoration: none"})

16. Arbel, J., Marchal, O. & Nipoti, B. (2020)\
    On the Hurwitz zeta function with an application to the beta-exponential distribution\
    *Journal of Inequalities and Applications*, 89 ([arXiv](https://arxiv.org/abs/1909.07026){style="text-decoration: none"})

17. Nipoti, B., Jara, A. & Guindani, M. (2018)\
    A Bayesian semiparametric partially PH model for clustered time-to-event data\
    *Scandinavian Journal of Statistics*, 45, 1016-1035 ([pdf](https://www.mat.uc.cl/~ajara/Publications_files/NJG_SJS.pdf){style="text-decoration: none"}, [SM](https://www.mat.uc.cl/~ajara/Publications_files/NJG_SJS_SM.pdf){style="text-decoration: none"})

18. Nipoti, B & Shen, W. (2018)\
    Contributed comment on Wade and Ghahramani's article\
    *Bayesian Analysis*, 13(2), 613-615

19. Canale, A., Lijoi, A., Nipoti, B. & Pruenster, I. (2017)\
    On the Pitman-Yor process with spike and slab base measure\
    *Biometrika*, 104(3), 681-697. ([pdf](http://www.carloalberto.org/assets/working-papers/no.501.pdf){style="text-decoration: none"})

20. Arbel, J., Favaro, S., Nipoti, B. & Teh, Y.W. (2017)\
    Bayesian nonparametric inference for discovery probabilities: credible intervals and large sample asymptotics\
    *Statistica Sinica*, 27(2), 839-858 ([arXiv](https://arxiv.org/abs/1506.04915){style="text-decoration: none"})

21. Favaro, S., Lijoi, A., Nava, C., Nipoti, B., Pruenster, I. & Teh, Y.W. (2016)\
    On the stick-breaking representation for homogeneous NRMIs\
    *Bayesian Analysis*, 11(3), 697-724.

22. Favaro, S., Nipoti, B. & Teh, Y.W. (2016)\
    Rediscovery of Good-Turing estimators via Bayesian nonparametrics\
    *Biometrics*, 72, 136-145. ([arXiv](https://arxiv.org/abs/1401.0303){style="text-decoration: none"})

23. Arbel, J., Lijoi, A. & Nipoti, B. (2016)\
    Full Bayesian inference with hazard mixture models\
    *Computational Statistics & Data Analysis*, 93, 359-372. ([arXiv](https://arxiv.org/abs/1405.6628){style="text-decoration: none"})

24. Favaro, S. Nipoti, B. & Teh, Y.W. (2015)\
    Random variate generation for Laguerre-type exponentially tilted α-stable distributions\
    *Electronic Journal of Statistics*, 9, 1230-1242

25. Favaro, S., Lomeli, M., Nipoti, B. & Teh, Y.W. (2014)\
    On the stick-breaking representation of σ-stable Poisson-Kingman models\
    *Electronic Journal of Statistics*, 8, 1063-1085

26. Favaro, S. & Nipoti, B. (2014)\
    Discussion of "On simulation and properties of the stable law" by L. Devroy and L. James"\
    *Statistical Methods & Applications*, 23(3), 365-369

27. Cesari, O., Favaro, S. & Nipoti, B. (2014)\
    Posterior analysis of rare variants in Gibbs-type species sampling models\
    *Journal of Multivariate Analysis*, 231, 79-98

28. Lijoi, A. & Nipoti, B. (2014)\
    A class of hazard rate mixtures for combining survival data from different experiments\
    *Journal of the American Statistical Association*, 109, 802-814

29. Lijoi, A., Nipoti, B. & Pruenster, I. (2014)\
    Bayesian inference with dependent normalized completely random measures\
    *Bernoulli*, 20(3), 1260-1291 ([arXiv](https://arxiv.org/abs/1407.0482){style="text-decoration: none"})

30. Lijoi, A., Nipoti, B. & Pruenster, I. (2014)\
    Dependent mixture models: clustering and borrowing information\
    *Computational Statistics & Data Analysis*, 71, 417-433

31. Arbel, J. & Nipoti, B. (2013)\
    Discussion on Müller and Mitra's "Bayesian Nonparametric Inference - Why and How"\
    *Bayesian Analysis*, 8, 326-328.

32. Ricca, R.L. & Nipoti, B. (2011)\
    Gauss' linking number revisited\
    *Journal of Knot Theory and Its Ramifications*, 20, 1325-1343

**Books and chapters in books**

33. Arbel, J., Lijoi, A. & Nipoti, B. (2015)\
    Bayesian Survival Model based on Moment Characterization\
    In *Proceedings of Baysm 2014*. Springer proceedings in Mathematics & Statistics, 126, 3-14. ([arXiv](https://arxiv.org/abs/1506.05269){style="text-decoration: none"})

34. Nipoti, B. (2012)\
    *Dependent Completely Random Measures and Statistical Applications*\
    Best Ph.D. thesis in statistics and applications. CLEUP ([page](https://www.cleup.it/product/13020761/dependent-completely-random-measures-and-statistical-applications){style="text-decoration: none"})

35. Ricca, R.L. & Nipoti, B. (2011)\
    Derivation and Interpretation of the Gauss Linking Number\
    In *Introductory Lectures on Knot Theory* (KauffmanL.H., Lambropoulou S., Jablan S., Przytycki J.H., eds), 428-501, Series on Knots and Everything, World Scientific Press

**Other publications**

36. D'Angelo, L., Nipoti, B. & Rigon, T. (2026)\
    A scale-only nonparametric mixture model for clustering covariance matrices: an application to olive oil chemical profiles\
    In *Scientific Meeting of the Italian Statistical Society*, Springer, 100-104.

37. D’Angelo L., Nipoti B. & Ongaro A. (2025)\
    Modeling related survival samples via dependent nonparametric mixtures\
    In *Statistics for Innovation III, Conference proceedings of SIS 2025*, Springer, 73-78.

38. Barile, F., Lunagomez, S. & Nipoti, B. (2024)\
    Clustering multiple networks data with an application to the EU food trade market\
    *Proceedings of 2024 Conference of the Italian Statistical Society*

39. D'Angelo, L., Ongaro, A., & Nipoti, B. (2024)\
    Two-level clustering of patients and hospitals via thinned dependent Dirichlet process mixtures\
    *Proceedings of 2024 Conference of the Italian Statistical Society*

40. Corradin, R., Nieto-Barajas, L. & Nipoti, B. (2020)\
    Pitman-Yor mixtures for survival data stratification\
    *Proceedings of 2020 Conference of the Italian Statistical Society*

41. Canale, A., Corradin, R. & Nipoti, B. (2019)\
    Galaxy color distribution estimation via dependent nonparametric mixtures\
    *Proceedings of 2019 Conference of the Italian Statistical Society* ([pdf](files/Corradin_et_al_SIS_2019.pdf){style="text-decoration: none"})

42. Arbel, J., Favaro, S., Nipoti, B. & Teh, Y.W. (2016)\
    On Bayesian nonparametric inference for discovery probabilities\
    *Proceedings of the 49th Scientific Meeting of the Italian Statistical Society*

43. Arbel, J., Favaro, S., Nipoti, B. & Teh, Y.W. (2016)\
    Discovery Probabilities when Uncertainty Matters\
    *48e Journées de la Statistique de la SFdS*

44. Lijoi, A., Nipoti, B. & Pruenster, I. (2015)\
    A Bayesian nonparametric model for clustering and borrowing information\
    *Proceedings of 10th scientific Meeting of the Classification and Data Analysis Group*

45. Favaro, S., Nipoti, B. & Teh, Y.W. (2015)\
    On a class of smoothed Good-Turing estimators\
    *Proceedings of the SIS2015 Statistical Conference*

46. Favaro, S. & Nipoti, B. (2014)\
    Uncertainty quantification for Bayesian nonparametric estimators of rare species variety\
    *Proceedings of the 47th Scientific Meeting of the Italian Statistical Society*

47. Lijoi, A., Nipoti, B. & Pruenster, I. (2014)\
    A Bayesian nonparametric model for combining data from different experiments\
    *Proceedings of the 47th Scientific Meeting of the Italian Statistical Society*

48. Favaro, S., Lomeli, M., Nipoti, B. & Teh, Y.W. (2013)\
    Stick-breaking representations of 1/2-stable Poisson-Kingman models\
    *Proceedings S.Co 2013*

49. Lijoi, A. & Nipoti, B. (2012)\
    Two classes of bivariate distributions on the unit square\
    *Carlo Alberto Notebooks* ([pdf](https://www.carloalberto.org/wp-content/uploads/2018/11/no.238.pdf){style="text-decoration: none"})
